version: 2
updates:
- package-ecosystem: bundler
  directory: "/test_rails_server"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rails
    versions:
    - 5.2.4.4
    - 5.2.4.5
